#!/bin/sh
UNAME=`uname`;
case "$1" in
# we only allow executing these commands
SetLocalRTC)
    if [ $UNAME = "FreeBSD" -a "$2" != "" ]; then
    export LC_ALL=C
        if [ $2 = "True" ]; then
        /usr/bin/touch /etc/wall_cmos_clock
        /sbin/adjkerntz -i
        elif [ $2 = "False" ] && [ -f "/etc/wall_cmos_clock" ]; then
        rm /etc/wall_cmos_clock
        fi
    fi
    ;;
SetNTP)
    if [ $UNAME = "FreeBSD" -a "$2" != "" ]; then
    export LC_ALL=C
        if [ "$2" = "False" ]; then
        /usr/sbin/sysrc "ntpd_enable=NO";
        /usr/sbin/service "ntpd" "onestop";

        elif [ "$2" = "True" ]; then
        /usr/sbin/sysrc "ntpd_enable=YES";
        /usr/sbin/service "ntpd" "start"
        fi;
    fi
    ;;
SetTime)
    if [ $UNAME = "FreeBSD" -a "$2" != "" ]; then
        export LC_ALL=C
        /bin/date "$2";

    fi
    ;;

SetTimezone)
    if [ $UNAME = "FreeBSD" -a "$2" != "" ]; then
        export LC_ALL=C
        /usr/sbin/tzsetup "$2";
    fi
    ;;
*)
    echo "Not allowed";
    exit 1;
    ;;
esac;

